# Generated by Django 5.2.17 on 2026-09-04 16:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('code', models.SlugField(max_length=20, unique=True)),
                ('commission_rate', models.DecimalField(decimal_places=3, max_digits=4)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('city', models.CharField(max_length=80)),
                ('rack_rate', models.DecimalField(decimal_places=2, max_digits=8)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ChannelPartner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partners', to='rates.channel')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='channel_partner', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RatePlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('min_stay_nights', models.PositiveSmallIntegerField(default=1)),
                ('cancellation_days', models.PositiveSmallIntegerField(default=1)),
                ('active', models.BooleanField(default=True)),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rate_plans', to='rates.channel')),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rate_plans', to='rates.hotel')),
            ],
            options={
                'ordering': ['channel__name', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ChannelRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('floor_price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('max_discount_pct', models.PositiveSmallIntegerField()),
                ('min_stay_nights', models.PositiveSmallIntegerField(default=1)),
                ('default_cancellation_days', models.PositiveSmallIntegerField(default=1)),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='rates.channel')),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='channel_rules', to='rates.hotel')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('channel', 'hotel'), name='one_rule_per_channel_and_hotel')],
            },
        ),
    ]
